### ISSUE TITLE
`change_index` not working for a summed term

### ISSUE THREAD

**Issue by Papageno2** [qojulia/QuantumCumulants.jl#196]
I have successfully used the following expression:
`change_index(σ(1,2,j),j,i) =`$\sigma_i^{12}$, It works as expected!

However, when attempting to calculate the product of collective operators, such as:
-  $\sum_i\sigma^{12}_i \sum_i \sigma^{23}_i$;
-  $\sum_i\sigma^{12}_i \sum_i \sigma^{12}_i$;

Using the code:
```julia
j = Index(h,:j,N,ha)

h1 = Σ(σ(1,2,j),j);

h1*h1
```
I encountered an error: "Specification of an extra Index is needed!"

Yet, if I utilize:
```julia
change_index(h1, j, i) 
``` 
It still returns $\sum_{j}^N\sigma_j^{12}$. Although I understand that h1 is a sum that is not dependent on the index j, the h1 * h1 operation requires a different index label.

Any insights on resolving this issue would be greatly appreciated!

**Comment by Papageno2** [comment]
there maybe a bug for the conjugate of complex coeficient:

```
@cnumbers  Ω_1 

hc = FockSpace(:cavity);
ha = NLevelSpace(:a, 4);
h = hc⊗ha

σ(α,β,i) = IndexedOperator(Transition(h, :σ, α, β),i)
k = Index(h,:k,N,ha)
j = Index(h,:j,N,ha)
i = Index(h,:i,N,ha)

h1e = Ω_1*σ(3,4,j);

change_index(h1e, j,i)'*∑(h1e,j)
```
it returns:
<img width="310" alt="image" src="https://github.com/qojulia/QuantumCumulants.jl/assets/40128584/3fe1f748-bc6b-4788-9530-5459ce61a661">

<img width="279" alt="image" src="https://github.com/qojulia/QuantumCumulants.jl/assets/40128584/ca6bbf63-8f0b-49a0-a07f-e249d82947e0">

**Comment by ChristophHotter** [comment]
Sorry for the late reply. 

Regarding your first [part](https://github.com/qojulia/QuantumCumulants.jl/issues/196#issue-2164734094): 

So far the function `change_index` does not work for sums but I think I can add a method if needed. 
Something like:

```
function change_index(S::SingleSum, i::Index, j::Index) 
    (j ∈ S.non_equal_indices) && error("Index $(j) is in the non-equal index list.")
    if S.sum_index == i
        return SingleSum(change_index(S.term,i,j), j, replace(S.non_equal_indices, i=>j), S.metadata)
    end        
    return S
end
```

There are two other alternatives.
You can define a second sum with a different index: 

```
h1i = Σ(σ(1,2,i),i)
h1j = Σ(σ(1,2,j),j)
h1i*h1j
```
or you can specify the extra index in the multiplication: 

`*(h1i,h1i;ind=j)`

For the second [part](https://github.com/qojulia/QuantumCumulants.jl/issues/196#issuecomment-1974755785) I think it is just a printing problem. If you look at the expression in the terminal you see a `conj(Ω_1)`.  
[Additionally, I think that the expression `∑(h1e,j)*∑(h1e,i)'`  does not make much sense, since you have a sum over `i` on an expression with index `j` only.]
