### ISSUE TITLE
Latex displays wrong expression

### ISSUE THREAD

**Issue by oameye** [qojulia/QuantumCumulants.jl#217]
```julia
using QuantumCumulants
using ModelingToolkit

# Hilbertspace
hc = FockSpace(:cavity)

# Operators
@qnumbers a::Destroy(hc)

# Parameters
@variables Δ::Real U::Real G::Real κ::Real

# Hamiltonian
H = -Δ * a' * a + U * a' * a + U * a' * a' * a * a / 2 - G * (a' * a' + a * a) / 2

# Jump operators & rates
J = [a]
rates = [κ];

# Derive equations
ops = [a']
eqs = meanfield(ops, H; order=1)

# Complete equations
eqs_completed = complete(eqs)
```
displays in my notebook
![image](https://github.com/user-attachments/assets/13376a9e-22c5-4619-8821-aab33a0246ae)
However, in the repl:
![image](https://github.com/user-attachments/assets/9ea35181-f7a5-422a-87f8-b9c33dd5e540)

It forgets to print the bracket in the latex output

**Comment by david-pl** [comment]
My guess, without checking in detail: since the latest release, complex number expressions are not always `<: Symbolic{CNumber}` anymore, but `<: Symbolic{Complex{Real}}`, so our latexify recipe doesn't apply anymore. If that's the case, the problem is that we shouldn't fix it here but in Symbolics since defining a latexify recipe for `Symbolic{Complex{Real}}` here would be type piracy.

**Comment by david-pl** [comment]
Okay I did some digging and it's not a bug in Symbolics. Somewhere in our latexify recipe the `Complex{Num}` that is $U - \Delta i$ gets parsed incorrectly. It's odd though, because the latexify recipes just return an Expr and doing `QuantumCumulants._to_expression(eqs_completed.equations[1].rhs)` gives

```
:((U - Δ * im) * AVG(dagger(a)) + (-G * im) * AVG(a) + (U * im) * AVG(dagger(a)) ^ 2 * AVG(a))
```

which seems correct.

**Comment by oameye** [comment]
Cool thanks😊
